# Displayname template for LinkedIn users.
# .FirstName is replaced with the first name
# .LastName is replaced with the last name
displayname_template: "{{ with .Organization }}{{ . }}{{ else }}{{ .FirstName }} {{ .LastName }}{{ end }} (LinkedIn)"
